services:
  database:
    image: postgres:17-alpine
    container_name: example-user-auth__database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example-user-auth
    volumes:
      - example-user-auth__volume:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - example-user-auth__network
  
  backend:
    build:
      context: ./backend
    container_name: example-user-auth__backend
    environment:
      POSTGRESQL_URL: postgresql://postgres:root@database:5432/example-user-auth
    depends_on:
      - database
    networks:
      - example-user-auth__network

  frontend:
    build:
      context: ./frontend
    container_name: example-user-auth__frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - example-user-auth__network
  
volumes:
  example-user-auth__volume:

networks:
  example-user-auth__network:
    driver: bridge